development:
  adapter: postgresql
  database: db/storedom_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/storedom_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/storedom
  pool: 5
  timeout: 5000
